// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design implementation internals
// See Vsystolic_array_tb.h for the primary calling header

#include "Vsystolic_array_tb__pch.h"
#include "Vsystolic_array_tb__Syms.h"
#include "Vsystolic_array_tb___024root.h"

VlCoroutine Vsystolic_array_tb_systolic_array_tb___eval_initial__TOP__systolic_array_tb__Vtiming__0(Vsystolic_array_tb_systolic_array_tb* vlSelf);
VlCoroutine Vsystolic_array_tb_systolic_array_tb___eval_initial__TOP__systolic_array_tb__Vtiming__1(Vsystolic_array_tb_systolic_array_tb* vlSelf);

void Vsystolic_array_tb___024root___eval_initial(Vsystolic_array_tb___024root* vlSelf) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vsystolic_array_tb___024root___eval_initial\n"); );
    Vsystolic_array_tb__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    vlSelfRef.__Vm_traceActivity[1U] = 1U;
    Vsystolic_array_tb_systolic_array_tb___eval_initial__TOP__systolic_array_tb__Vtiming__0((&vlSymsp->TOP__systolic_array_tb));
    Vsystolic_array_tb_systolic_array_tb___eval_initial__TOP__systolic_array_tb__Vtiming__1((&vlSymsp->TOP__systolic_array_tb));
    vlSelfRef.__Vtrigprevexpr___TOP__systolic_array_tb____PVT__tb_clk__0 
        = vlSymsp->TOP__systolic_array_tb.__PVT__tb_clk;
    vlSelfRef.__Vtrigprevexpr___TOP__systolic_array_tb____PVT__tb_nRST__0 
        = vlSymsp->TOP__systolic_array_tb.__PVT__tb_nRST;
}

#ifdef VL_DEBUG
VL_ATTR_COLD void Vsystolic_array_tb___024root___dump_triggers__act(Vsystolic_array_tb___024root* vlSelf);
#endif  // VL_DEBUG

void Vsystolic_array_tb___024root___eval_triggers__act(Vsystolic_array_tb___024root* vlSelf) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vsystolic_array_tb___024root___eval_triggers__act\n"); );
    Vsystolic_array_tb__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    vlSelfRef.__VactTriggered.set(0U, ((IData)(vlSymsp->TOP__systolic_array_tb.__PVT__tb_clk) 
                                       & (~ (IData)(vlSelfRef.__Vtrigprevexpr___TOP__systolic_array_tb____PVT__tb_clk__0))));
    vlSelfRef.__VactTriggered.set(1U, ((~ (IData)(vlSymsp->TOP__systolic_array_tb.__PVT__tb_nRST)) 
                                       & (IData)(vlSelfRef.__Vtrigprevexpr___TOP__systolic_array_tb____PVT__tb_nRST__0)));
    vlSelfRef.__VactTriggered.set(2U, ((~ (IData)(vlSymsp->TOP__systolic_array_tb.__PVT__tb_clk)) 
                                       & (IData)(vlSelfRef.__Vtrigprevexpr___TOP__systolic_array_tb____PVT__tb_clk__0)));
    vlSelfRef.__VactTriggered.set(3U, vlSelfRef.__VdlySched.awaitingCurrentTime());
    vlSelfRef.__Vtrigprevexpr___TOP__systolic_array_tb____PVT__tb_clk__0 
        = vlSymsp->TOP__systolic_array_tb.__PVT__tb_clk;
    vlSelfRef.__Vtrigprevexpr___TOP__systolic_array_tb____PVT__tb_nRST__0 
        = vlSymsp->TOP__systolic_array_tb.__PVT__tb_nRST;
#ifdef VL_DEBUG
    if (VL_UNLIKELY(vlSymsp->_vm_contextp__->debug())) {
        Vsystolic_array_tb___024root___dump_triggers__act(vlSelf);
    }
#endif
}

void Vsystolic_array_tb_sysarr_control_unit___act_comb__TOP__systolic_array_tb__DUT__cu_inst__0(Vsystolic_array_tb_sysarr_control_unit* vlSelf);
void Vsystolic_array_tb_systolic_array___act_comb__TOP__systolic_array_tb__DUT__0(Vsystolic_array_tb_systolic_array* vlSelf);

void Vsystolic_array_tb___024root___eval_act(Vsystolic_array_tb___024root* vlSelf) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vsystolic_array_tb___024root___eval_act\n"); );
    Vsystolic_array_tb__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    if ((0xdULL & vlSelfRef.__VactTriggered.word(0U))) {
        Vsystolic_array_tb_sysarr_control_unit___act_comb__TOP__systolic_array_tb__DUT__cu_inst__0((&vlSymsp->TOP__systolic_array_tb__DUT__cu_inst));
        vlSelfRef.__Vm_traceActivity[2U] = 1U;
        Vsystolic_array_tb_systolic_array___act_comb__TOP__systolic_array_tb__DUT__0((&vlSymsp->TOP__systolic_array_tb__DUT));
    }
}

void Vsystolic_array_tb_systolic_array___nba_sequent__TOP__systolic_array_tb__DUT__0(Vsystolic_array_tb_systolic_array* vlSelf);
void Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__0__KET____DOT__genblk1__BRA__1__KET____DOT__mac_inst__0(Vsystolic_array_tb_sysarr_MAC* vlSelf);
void Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__0__KET____DOT__genblk1__BRA__2__KET____DOT__mac_inst__0(Vsystolic_array_tb_sysarr_MAC* vlSelf);
void Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__0__KET____DOT__genblk1__BRA__3__KET____DOT__mac_inst__0(Vsystolic_array_tb_sysarr_MAC* vlSelf);
void Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__1__KET____DOT__genblk1__BRA__0__KET____DOT__mac_inst__0(Vsystolic_array_tb_sysarr_MAC* vlSelf);
void Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__1__KET____DOT__genblk1__BRA__1__KET____DOT__mac_inst__0(Vsystolic_array_tb_sysarr_MAC* vlSelf);
void Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__1__KET____DOT__genblk1__BRA__2__KET____DOT__mac_inst__0(Vsystolic_array_tb_sysarr_MAC* vlSelf);
void Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__1__KET____DOT__genblk1__BRA__3__KET____DOT__mac_inst__0(Vsystolic_array_tb_sysarr_MAC* vlSelf);
void Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__2__KET____DOT__genblk1__BRA__0__KET____DOT__mac_inst__0(Vsystolic_array_tb_sysarr_MAC* vlSelf);
void Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__2__KET____DOT__genblk1__BRA__1__KET____DOT__mac_inst__0(Vsystolic_array_tb_sysarr_MAC* vlSelf);
void Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__2__KET____DOT__genblk1__BRA__2__KET____DOT__mac_inst__0(Vsystolic_array_tb_sysarr_MAC* vlSelf);
void Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__2__KET____DOT__genblk1__BRA__3__KET____DOT__mac_inst__0(Vsystolic_array_tb_sysarr_MAC* vlSelf);
void Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__3__KET____DOT__genblk1__BRA__0__KET____DOT__mac_inst__0(Vsystolic_array_tb_sysarr_MAC* vlSelf);
void Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__3__KET____DOT__genblk1__BRA__1__KET____DOT__mac_inst__0(Vsystolic_array_tb_sysarr_MAC* vlSelf);
void Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__3__KET____DOT__genblk1__BRA__2__KET____DOT__mac_inst__0(Vsystolic_array_tb_sysarr_MAC* vlSelf);
void Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__3__KET____DOT__genblk1__BRA__3__KET____DOT__mac_inst__0(Vsystolic_array_tb_sysarr_MAC* vlSelf);
void Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__0__KET____DOT__genblk1__BRA__0__KET____DOT__mac_inst__0(Vsystolic_array_tb_sysarr_MAC* vlSelf);
void Vsystolic_array_tb_sysarr_control_unit___nba_sequent__TOP__systolic_array_tb__DUT__cu_inst__0(Vsystolic_array_tb_sysarr_control_unit* vlSelf);
void Vsystolic_array_tb_systolic_array___nba_sequent__TOP__systolic_array_tb__DUT__1(Vsystolic_array_tb_systolic_array* vlSelf);
void Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__1__KET____DOT__genblk1__BRA__0__KET____DOT__mac_inst__1(Vsystolic_array_tb_sysarr_MAC* vlSelf);
void Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__1__KET____DOT__genblk1__BRA__1__KET____DOT__mac_inst__1(Vsystolic_array_tb_sysarr_MAC* vlSelf);
void Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__1__KET____DOT__genblk1__BRA__2__KET____DOT__mac_inst__1(Vsystolic_array_tb_sysarr_MAC* vlSelf);
void Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__1__KET____DOT__genblk1__BRA__3__KET____DOT__mac_inst__1(Vsystolic_array_tb_sysarr_MAC* vlSelf);
void Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__2__KET____DOT__genblk1__BRA__0__KET____DOT__mac_inst__1(Vsystolic_array_tb_sysarr_MAC* vlSelf);
void Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__2__KET____DOT__genblk1__BRA__1__KET____DOT__mac_inst__1(Vsystolic_array_tb_sysarr_MAC* vlSelf);
void Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__2__KET____DOT__genblk1__BRA__2__KET____DOT__mac_inst__1(Vsystolic_array_tb_sysarr_MAC* vlSelf);
void Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__2__KET____DOT__genblk1__BRA__3__KET____DOT__mac_inst__1(Vsystolic_array_tb_sysarr_MAC* vlSelf);
void Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__3__KET____DOT__genblk1__BRA__0__KET____DOT__mac_inst__1(Vsystolic_array_tb_sysarr_MAC* vlSelf);
void Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__3__KET____DOT__genblk1__BRA__1__KET____DOT__mac_inst__1(Vsystolic_array_tb_sysarr_MAC* vlSelf);
void Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__3__KET____DOT__genblk1__BRA__2__KET____DOT__mac_inst__1(Vsystolic_array_tb_sysarr_MAC* vlSelf);
void Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__3__KET____DOT__genblk1__BRA__3__KET____DOT__mac_inst__1(Vsystolic_array_tb_sysarr_MAC* vlSelf);
void Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__0__KET____DOT__genblk1__BRA__0__KET____DOT__mac_inst__1(Vsystolic_array_tb_sysarr_MAC* vlSelf);
void Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__0__KET____DOT__genblk1__BRA__1__KET____DOT__mac_inst__1(Vsystolic_array_tb_sysarr_MAC* vlSelf);
void Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__0__KET____DOT__genblk1__BRA__2__KET____DOT__mac_inst__1(Vsystolic_array_tb_sysarr_MAC* vlSelf);
void Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__0__KET____DOT__genblk1__BRA__3__KET____DOT__mac_inst__1(Vsystolic_array_tb_sysarr_MAC* vlSelf);
void Vsystolic_array_tb_sysarr_control_unit___nba_sequent__TOP__systolic_array_tb__DUT__cu_inst__1(Vsystolic_array_tb_sysarr_control_unit* vlSelf);
void Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__0__KET____DOT__genblk1__BRA__1__KET____DOT__mac_inst__2(Vsystolic_array_tb_sysarr_MAC* vlSelf);
void Vsystolic_array_tb_sysarr_control_unit___nba_sequent__TOP__systolic_array_tb__DUT__cu_inst__2(Vsystolic_array_tb_sysarr_control_unit* vlSelf);
void Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__0__KET____DOT__genblk1__BRA__0__KET____DOT__mac_inst__2(Vsystolic_array_tb_sysarr_MAC* vlSelf);
void Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__0__KET____DOT__genblk1__BRA__1__KET____DOT__mac_inst__3(Vsystolic_array_tb_sysarr_MAC* vlSelf);
void Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__0__KET____DOT__genblk1__BRA__2__KET____DOT__mac_inst__3(Vsystolic_array_tb_sysarr_MAC* vlSelf);
void Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__0__KET____DOT__genblk1__BRA__3__KET____DOT__mac_inst__3(Vsystolic_array_tb_sysarr_MAC* vlSelf);
void Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__1__KET____DOT__genblk1__BRA__0__KET____DOT__mac_inst__3(Vsystolic_array_tb_sysarr_MAC* vlSelf);
void Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__1__KET____DOT__genblk1__BRA__1__KET____DOT__mac_inst__3(Vsystolic_array_tb_sysarr_MAC* vlSelf);
void Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__1__KET____DOT__genblk1__BRA__2__KET____DOT__mac_inst__3(Vsystolic_array_tb_sysarr_MAC* vlSelf);
void Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__1__KET____DOT__genblk1__BRA__3__KET____DOT__mac_inst__3(Vsystolic_array_tb_sysarr_MAC* vlSelf);
void Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__2__KET____DOT__genblk1__BRA__0__KET____DOT__mac_inst__3(Vsystolic_array_tb_sysarr_MAC* vlSelf);
void Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__2__KET____DOT__genblk1__BRA__1__KET____DOT__mac_inst__3(Vsystolic_array_tb_sysarr_MAC* vlSelf);
void Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__2__KET____DOT__genblk1__BRA__2__KET____DOT__mac_inst__3(Vsystolic_array_tb_sysarr_MAC* vlSelf);
void Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__2__KET____DOT__genblk1__BRA__3__KET____DOT__mac_inst__3(Vsystolic_array_tb_sysarr_MAC* vlSelf);
void Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__3__KET____DOT__genblk1__BRA__0__KET____DOT__mac_inst__3(Vsystolic_array_tb_sysarr_MAC* vlSelf);
void Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__3__KET____DOT__genblk1__BRA__1__KET____DOT__mac_inst__3(Vsystolic_array_tb_sysarr_MAC* vlSelf);
void Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__3__KET____DOT__genblk1__BRA__2__KET____DOT__mac_inst__3(Vsystolic_array_tb_sysarr_MAC* vlSelf);
void Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__3__KET____DOT__genblk1__BRA__3__KET____DOT__mac_inst__3(Vsystolic_array_tb_sysarr_MAC* vlSelf);
void Vsystolic_array_tb_sysarr_control_unit___nba_comb__TOP__systolic_array_tb__DUT__cu_inst__0(Vsystolic_array_tb_sysarr_control_unit* vlSelf);
void Vsystolic_array_tb_systolic_array___nba_comb__TOP__systolic_array_tb__DUT__0(Vsystolic_array_tb_systolic_array* vlSelf);
void Vsystolic_array_tb_systolic_array_tb___nba_sequent__TOP__systolic_array_tb__0(Vsystolic_array_tb_systolic_array_tb* vlSelf);
void Vsystolic_array_tb_sysarr_control_unit___nba_comb__TOP__systolic_array_tb__DUT__cu_inst__1(Vsystolic_array_tb_sysarr_control_unit* vlSelf);
void Vsystolic_array_tb_systolic_array___nba_comb__TOP__systolic_array_tb__DUT__1(Vsystolic_array_tb_systolic_array* vlSelf);
void Vsystolic_array_tb_systolic_array___nba_sequent__TOP__systolic_array_tb__DUT__2(Vsystolic_array_tb_systolic_array* vlSelf);

void Vsystolic_array_tb___024root___eval_nba(Vsystolic_array_tb___024root* vlSelf) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vsystolic_array_tb___024root___eval_nba\n"); );
    Vsystolic_array_tb__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    if ((3ULL & vlSelfRef.__VnbaTriggered.word(0U))) {
        Vsystolic_array_tb_systolic_array___nba_sequent__TOP__systolic_array_tb__DUT__0((&vlSymsp->TOP__systolic_array_tb__DUT));
        vlSelfRef.__Vm_traceActivity[3U] = 1U;
        Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__0__KET____DOT__genblk1__BRA__1__KET____DOT__mac_inst__0((&vlSymsp->TOP__systolic_array_tb__DUT__genblk4__BRA__0__KET____DOT__genblk1__BRA__1__KET____DOT__mac_inst));
        Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__0__KET____DOT__genblk1__BRA__2__KET____DOT__mac_inst__0((&vlSymsp->TOP__systolic_array_tb__DUT__genblk4__BRA__0__KET____DOT__genblk1__BRA__2__KET____DOT__mac_inst));
        Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__0__KET____DOT__genblk1__BRA__3__KET____DOT__mac_inst__0((&vlSymsp->TOP__systolic_array_tb__DUT__genblk4__BRA__0__KET____DOT__genblk1__BRA__3__KET____DOT__mac_inst));
        Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__1__KET____DOT__genblk1__BRA__0__KET____DOT__mac_inst__0((&vlSymsp->TOP__systolic_array_tb__DUT__genblk4__BRA__1__KET____DOT__genblk1__BRA__0__KET____DOT__mac_inst));
        Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__1__KET____DOT__genblk1__BRA__1__KET____DOT__mac_inst__0((&vlSymsp->TOP__systolic_array_tb__DUT__genblk4__BRA__1__KET____DOT__genblk1__BRA__1__KET____DOT__mac_inst));
        Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__1__KET____DOT__genblk1__BRA__2__KET____DOT__mac_inst__0((&vlSymsp->TOP__systolic_array_tb__DUT__genblk4__BRA__1__KET____DOT__genblk1__BRA__2__KET____DOT__mac_inst));
        Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__1__KET____DOT__genblk1__BRA__3__KET____DOT__mac_inst__0((&vlSymsp->TOP__systolic_array_tb__DUT__genblk4__BRA__1__KET____DOT__genblk1__BRA__3__KET____DOT__mac_inst));
        Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__2__KET____DOT__genblk1__BRA__0__KET____DOT__mac_inst__0((&vlSymsp->TOP__systolic_array_tb__DUT__genblk4__BRA__2__KET____DOT__genblk1__BRA__0__KET____DOT__mac_inst));
        Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__2__KET____DOT__genblk1__BRA__1__KET____DOT__mac_inst__0((&vlSymsp->TOP__systolic_array_tb__DUT__genblk4__BRA__2__KET____DOT__genblk1__BRA__1__KET____DOT__mac_inst));
        Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__2__KET____DOT__genblk1__BRA__2__KET____DOT__mac_inst__0((&vlSymsp->TOP__systolic_array_tb__DUT__genblk4__BRA__2__KET____DOT__genblk1__BRA__2__KET____DOT__mac_inst));
        Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__2__KET____DOT__genblk1__BRA__3__KET____DOT__mac_inst__0((&vlSymsp->TOP__systolic_array_tb__DUT__genblk4__BRA__2__KET____DOT__genblk1__BRA__3__KET____DOT__mac_inst));
        Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__3__KET____DOT__genblk1__BRA__0__KET____DOT__mac_inst__0((&vlSymsp->TOP__systolic_array_tb__DUT__genblk4__BRA__3__KET____DOT__genblk1__BRA__0__KET____DOT__mac_inst));
        Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__3__KET____DOT__genblk1__BRA__1__KET____DOT__mac_inst__0((&vlSymsp->TOP__systolic_array_tb__DUT__genblk4__BRA__3__KET____DOT__genblk1__BRA__1__KET____DOT__mac_inst));
        Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__3__KET____DOT__genblk1__BRA__2__KET____DOT__mac_inst__0((&vlSymsp->TOP__systolic_array_tb__DUT__genblk4__BRA__3__KET____DOT__genblk1__BRA__2__KET____DOT__mac_inst));
        Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__3__KET____DOT__genblk1__BRA__3__KET____DOT__mac_inst__0((&vlSymsp->TOP__systolic_array_tb__DUT__genblk4__BRA__3__KET____DOT__genblk1__BRA__3__KET____DOT__mac_inst));
        Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__0__KET____DOT__genblk1__BRA__0__KET____DOT__mac_inst__0((&vlSymsp->TOP__systolic_array_tb__DUT__genblk4__BRA__0__KET____DOT__genblk1__BRA__0__KET____DOT__mac_inst));
        Vsystolic_array_tb_sysarr_control_unit___nba_sequent__TOP__systolic_array_tb__DUT__cu_inst__0((&vlSymsp->TOP__systolic_array_tb__DUT__cu_inst));
        Vsystolic_array_tb_systolic_array___nba_sequent__TOP__systolic_array_tb__DUT__1((&vlSymsp->TOP__systolic_array_tb__DUT));
        Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__1__KET____DOT__genblk1__BRA__0__KET____DOT__mac_inst__1((&vlSymsp->TOP__systolic_array_tb__DUT__genblk4__BRA__1__KET____DOT__genblk1__BRA__0__KET____DOT__mac_inst));
        Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__1__KET____DOT__genblk1__BRA__1__KET____DOT__mac_inst__1((&vlSymsp->TOP__systolic_array_tb__DUT__genblk4__BRA__1__KET____DOT__genblk1__BRA__1__KET____DOT__mac_inst));
        Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__1__KET____DOT__genblk1__BRA__2__KET____DOT__mac_inst__1((&vlSymsp->TOP__systolic_array_tb__DUT__genblk4__BRA__1__KET____DOT__genblk1__BRA__2__KET____DOT__mac_inst));
        Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__1__KET____DOT__genblk1__BRA__3__KET____DOT__mac_inst__1((&vlSymsp->TOP__systolic_array_tb__DUT__genblk4__BRA__1__KET____DOT__genblk1__BRA__3__KET____DOT__mac_inst));
        Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__2__KET____DOT__genblk1__BRA__0__KET____DOT__mac_inst__1((&vlSymsp->TOP__systolic_array_tb__DUT__genblk4__BRA__2__KET____DOT__genblk1__BRA__0__KET____DOT__mac_inst));
        Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__2__KET____DOT__genblk1__BRA__1__KET____DOT__mac_inst__1((&vlSymsp->TOP__systolic_array_tb__DUT__genblk4__BRA__2__KET____DOT__genblk1__BRA__1__KET____DOT__mac_inst));
        Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__2__KET____DOT__genblk1__BRA__2__KET____DOT__mac_inst__1((&vlSymsp->TOP__systolic_array_tb__DUT__genblk4__BRA__2__KET____DOT__genblk1__BRA__2__KET____DOT__mac_inst));
        Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__2__KET____DOT__genblk1__BRA__3__KET____DOT__mac_inst__1((&vlSymsp->TOP__systolic_array_tb__DUT__genblk4__BRA__2__KET____DOT__genblk1__BRA__3__KET____DOT__mac_inst));
        Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__3__KET____DOT__genblk1__BRA__0__KET____DOT__mac_inst__1((&vlSymsp->TOP__systolic_array_tb__DUT__genblk4__BRA__3__KET____DOT__genblk1__BRA__0__KET____DOT__mac_inst));
        Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__3__KET____DOT__genblk1__BRA__1__KET____DOT__mac_inst__1((&vlSymsp->TOP__systolic_array_tb__DUT__genblk4__BRA__3__KET____DOT__genblk1__BRA__1__KET____DOT__mac_inst));
        Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__3__KET____DOT__genblk1__BRA__2__KET____DOT__mac_inst__1((&vlSymsp->TOP__systolic_array_tb__DUT__genblk4__BRA__3__KET____DOT__genblk1__BRA__2__KET____DOT__mac_inst));
        Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__3__KET____DOT__genblk1__BRA__3__KET____DOT__mac_inst__1((&vlSymsp->TOP__systolic_array_tb__DUT__genblk4__BRA__3__KET____DOT__genblk1__BRA__3__KET____DOT__mac_inst));
        Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__0__KET____DOT__genblk1__BRA__0__KET____DOT__mac_inst__1((&vlSymsp->TOP__systolic_array_tb__DUT__genblk4__BRA__0__KET____DOT__genblk1__BRA__0__KET____DOT__mac_inst));
        Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__0__KET____DOT__genblk1__BRA__1__KET____DOT__mac_inst__1((&vlSymsp->TOP__systolic_array_tb__DUT__genblk4__BRA__0__KET____DOT__genblk1__BRA__1__KET____DOT__mac_inst));
        Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__0__KET____DOT__genblk1__BRA__2__KET____DOT__mac_inst__1((&vlSymsp->TOP__systolic_array_tb__DUT__genblk4__BRA__0__KET____DOT__genblk1__BRA__2__KET____DOT__mac_inst));
        Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__0__KET____DOT__genblk1__BRA__3__KET____DOT__mac_inst__1((&vlSymsp->TOP__systolic_array_tb__DUT__genblk4__BRA__0__KET____DOT__genblk1__BRA__3__KET____DOT__mac_inst));
        Vsystolic_array_tb_sysarr_control_unit___nba_sequent__TOP__systolic_array_tb__DUT__cu_inst__1((&vlSymsp->TOP__systolic_array_tb__DUT__cu_inst));
        Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__0__KET____DOT__genblk1__BRA__1__KET____DOT__mac_inst__2((&vlSymsp->TOP__systolic_array_tb__DUT__genblk4__BRA__0__KET____DOT__genblk1__BRA__1__KET____DOT__mac_inst));
        Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__0__KET____DOT__genblk1__BRA__1__KET____DOT__mac_inst__2((&vlSymsp->TOP__systolic_array_tb__DUT__genblk4__BRA__0__KET____DOT__genblk1__BRA__2__KET____DOT__mac_inst));
        Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__0__KET____DOT__genblk1__BRA__1__KET____DOT__mac_inst__2((&vlSymsp->TOP__systolic_array_tb__DUT__genblk4__BRA__0__KET____DOT__genblk1__BRA__3__KET____DOT__mac_inst));
        Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__0__KET____DOT__genblk1__BRA__1__KET____DOT__mac_inst__2((&vlSymsp->TOP__systolic_array_tb__DUT__genblk4__BRA__1__KET____DOT__genblk1__BRA__0__KET____DOT__mac_inst));
        Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__0__KET____DOT__genblk1__BRA__1__KET____DOT__mac_inst__2((&vlSymsp->TOP__systolic_array_tb__DUT__genblk4__BRA__1__KET____DOT__genblk1__BRA__1__KET____DOT__mac_inst));
        Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__0__KET____DOT__genblk1__BRA__1__KET____DOT__mac_inst__2((&vlSymsp->TOP__systolic_array_tb__DUT__genblk4__BRA__1__KET____DOT__genblk1__BRA__2__KET____DOT__mac_inst));
        Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__0__KET____DOT__genblk1__BRA__1__KET____DOT__mac_inst__2((&vlSymsp->TOP__systolic_array_tb__DUT__genblk4__BRA__1__KET____DOT__genblk1__BRA__3__KET____DOT__mac_inst));
        Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__0__KET____DOT__genblk1__BRA__1__KET____DOT__mac_inst__2((&vlSymsp->TOP__systolic_array_tb__DUT__genblk4__BRA__2__KET____DOT__genblk1__BRA__0__KET____DOT__mac_inst));
        Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__0__KET____DOT__genblk1__BRA__1__KET____DOT__mac_inst__2((&vlSymsp->TOP__systolic_array_tb__DUT__genblk4__BRA__2__KET____DOT__genblk1__BRA__1__KET____DOT__mac_inst));
        Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__0__KET____DOT__genblk1__BRA__1__KET____DOT__mac_inst__2((&vlSymsp->TOP__systolic_array_tb__DUT__genblk4__BRA__2__KET____DOT__genblk1__BRA__2__KET____DOT__mac_inst));
        Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__0__KET____DOT__genblk1__BRA__1__KET____DOT__mac_inst__2((&vlSymsp->TOP__systolic_array_tb__DUT__genblk4__BRA__2__KET____DOT__genblk1__BRA__3__KET____DOT__mac_inst));
        Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__0__KET____DOT__genblk1__BRA__1__KET____DOT__mac_inst__2((&vlSymsp->TOP__systolic_array_tb__DUT__genblk4__BRA__3__KET____DOT__genblk1__BRA__0__KET____DOT__mac_inst));
        Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__0__KET____DOT__genblk1__BRA__1__KET____DOT__mac_inst__2((&vlSymsp->TOP__systolic_array_tb__DUT__genblk4__BRA__3__KET____DOT__genblk1__BRA__1__KET____DOT__mac_inst));
        Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__0__KET____DOT__genblk1__BRA__1__KET____DOT__mac_inst__2((&vlSymsp->TOP__systolic_array_tb__DUT__genblk4__BRA__3__KET____DOT__genblk1__BRA__2__KET____DOT__mac_inst));
        Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__0__KET____DOT__genblk1__BRA__1__KET____DOT__mac_inst__2((&vlSymsp->TOP__systolic_array_tb__DUT__genblk4__BRA__3__KET____DOT__genblk1__BRA__3__KET____DOT__mac_inst));
        Vsystolic_array_tb_sysarr_control_unit___nba_sequent__TOP__systolic_array_tb__DUT__cu_inst__2((&vlSymsp->TOP__systolic_array_tb__DUT__cu_inst));
        Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__0__KET____DOT__genblk1__BRA__0__KET____DOT__mac_inst__2((&vlSymsp->TOP__systolic_array_tb__DUT__genblk4__BRA__0__KET____DOT__genblk1__BRA__0__KET____DOT__mac_inst));
        Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__0__KET____DOT__genblk1__BRA__1__KET____DOT__mac_inst__3((&vlSymsp->TOP__systolic_array_tb__DUT__genblk4__BRA__0__KET____DOT__genblk1__BRA__1__KET____DOT__mac_inst));
        Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__0__KET____DOT__genblk1__BRA__2__KET____DOT__mac_inst__3((&vlSymsp->TOP__systolic_array_tb__DUT__genblk4__BRA__0__KET____DOT__genblk1__BRA__2__KET____DOT__mac_inst));
        Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__0__KET____DOT__genblk1__BRA__3__KET____DOT__mac_inst__3((&vlSymsp->TOP__systolic_array_tb__DUT__genblk4__BRA__0__KET____DOT__genblk1__BRA__3__KET____DOT__mac_inst));
        Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__1__KET____DOT__genblk1__BRA__0__KET____DOT__mac_inst__3((&vlSymsp->TOP__systolic_array_tb__DUT__genblk4__BRA__1__KET____DOT__genblk1__BRA__0__KET____DOT__mac_inst));
        Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__1__KET____DOT__genblk1__BRA__1__KET____DOT__mac_inst__3((&vlSymsp->TOP__systolic_array_tb__DUT__genblk4__BRA__1__KET____DOT__genblk1__BRA__1__KET____DOT__mac_inst));
        Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__1__KET____DOT__genblk1__BRA__2__KET____DOT__mac_inst__3((&vlSymsp->TOP__systolic_array_tb__DUT__genblk4__BRA__1__KET____DOT__genblk1__BRA__2__KET____DOT__mac_inst));
        Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__1__KET____DOT__genblk1__BRA__3__KET____DOT__mac_inst__3((&vlSymsp->TOP__systolic_array_tb__DUT__genblk4__BRA__1__KET____DOT__genblk1__BRA__3__KET____DOT__mac_inst));
        Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__2__KET____DOT__genblk1__BRA__0__KET____DOT__mac_inst__3((&vlSymsp->TOP__systolic_array_tb__DUT__genblk4__BRA__2__KET____DOT__genblk1__BRA__0__KET____DOT__mac_inst));
        Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__2__KET____DOT__genblk1__BRA__1__KET____DOT__mac_inst__3((&vlSymsp->TOP__systolic_array_tb__DUT__genblk4__BRA__2__KET____DOT__genblk1__BRA__1__KET____DOT__mac_inst));
        Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__2__KET____DOT__genblk1__BRA__2__KET____DOT__mac_inst__3((&vlSymsp->TOP__systolic_array_tb__DUT__genblk4__BRA__2__KET____DOT__genblk1__BRA__2__KET____DOT__mac_inst));
        Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__2__KET____DOT__genblk1__BRA__3__KET____DOT__mac_inst__3((&vlSymsp->TOP__systolic_array_tb__DUT__genblk4__BRA__2__KET____DOT__genblk1__BRA__3__KET____DOT__mac_inst));
        Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__3__KET____DOT__genblk1__BRA__0__KET____DOT__mac_inst__3((&vlSymsp->TOP__systolic_array_tb__DUT__genblk4__BRA__3__KET____DOT__genblk1__BRA__0__KET____DOT__mac_inst));
        Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__3__KET____DOT__genblk1__BRA__1__KET____DOT__mac_inst__3((&vlSymsp->TOP__systolic_array_tb__DUT__genblk4__BRA__3__KET____DOT__genblk1__BRA__1__KET____DOT__mac_inst));
        Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__3__KET____DOT__genblk1__BRA__2__KET____DOT__mac_inst__3((&vlSymsp->TOP__systolic_array_tb__DUT__genblk4__BRA__3__KET____DOT__genblk1__BRA__2__KET____DOT__mac_inst));
        Vsystolic_array_tb_sysarr_MAC___nba_sequent__TOP__systolic_array_tb__DUT__genblk4__BRA__3__KET____DOT__genblk1__BRA__3__KET____DOT__mac_inst__3((&vlSymsp->TOP__systolic_array_tb__DUT__genblk4__BRA__3__KET____DOT__genblk1__BRA__3__KET____DOT__mac_inst));
    }
    if ((0xdULL & vlSelfRef.__VnbaTriggered.word(0U))) {
        Vsystolic_array_tb_sysarr_control_unit___nba_comb__TOP__systolic_array_tb__DUT__cu_inst__0((&vlSymsp->TOP__systolic_array_tb__DUT__cu_inst));
        vlSelfRef.__Vm_traceActivity[4U] = 1U;
        Vsystolic_array_tb_systolic_array___nba_comb__TOP__systolic_array_tb__DUT__0((&vlSymsp->TOP__systolic_array_tb__DUT));
    }
    if ((1ULL & vlSelfRef.__VnbaTriggered.word(0U))) {
        Vsystolic_array_tb_systolic_array_tb___nba_sequent__TOP__systolic_array_tb__0((&vlSymsp->TOP__systolic_array_tb));
        vlSelfRef.__Vm_traceActivity[5U] = 1U;
    }
    if ((0xfULL & vlSelfRef.__VnbaTriggered.word(0U))) {
        Vsystolic_array_tb_sysarr_control_unit___nba_comb__TOP__systolic_array_tb__DUT__cu_inst__1((&vlSymsp->TOP__systolic_array_tb__DUT__cu_inst));
        vlSelfRef.__Vm_traceActivity[6U] = 1U;
        Vsystolic_array_tb_systolic_array___nba_comb__TOP__systolic_array_tb__DUT__1((&vlSymsp->TOP__systolic_array_tb__DUT));
    }
    if ((3ULL & vlSelfRef.__VnbaTriggered.word(0U))) {
        Vsystolic_array_tb_systolic_array___nba_sequent__TOP__systolic_array_tb__DUT__2((&vlSymsp->TOP__systolic_array_tb__DUT));
        vlSelfRef.__Vm_traceActivity[7U] = 1U;
    }
}
